package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JavaProject generated by hbm2java
 */
@Entity
@Table(name = "java_project", catalog = "aminfo")
public class JavaProject implements java.io.Serializable {

	private Integer id;
	private String technologies;
	private String chapter;
	private String title;
	private String desc;
	private String attachments;
	private Date datetime;
	private Integer status;
	private Integer totalView;
	private String sourceCodeLink;
	private String sourceCodeSize;
	private Integer totalDownload;

	public JavaProject() {
	}

	public JavaProject(Date datetime) {
		this.datetime = datetime;
	}

	public JavaProject(String technologies, String chapter, String title, String desc, String attachments,
			Date datetime, Integer status, Integer totalView, String sourceCodeLink, String sourceCodeSize,
			Integer totalDownload) {
		this.technologies = technologies;
		this.chapter = chapter;
		this.title = title;
		this.desc = desc;
		this.attachments = attachments;
		this.datetime = datetime;
		this.status = status;
		this.totalView = totalView;
		this.sourceCodeLink = sourceCodeLink;
		this.sourceCodeSize = sourceCodeSize;
		this.totalDownload = totalDownload;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "technologies", length = 200)
	public String getTechnologies() {
		return this.technologies;
	}

	public void setTechnologies(String technologies) {
		this.technologies = technologies;
	}

	@Column(name = "chapter", length = 50)
	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	@Column(name = "title", length = 2000)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "desc", length = 65535)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "attachments", length = 200)
	public String getAttachments() {
		return this.attachments;
	}

	public void setAttachments(String attachments) {
		this.attachments = attachments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", nullable = false, length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "total_view")
	public Integer getTotalView() {
		return this.totalView;
	}

	public void setTotalView(Integer totalView) {
		this.totalView = totalView;
	}

	@Column(name = "source_code_link", length = 200)
	public String getSourceCodeLink() {
		return this.sourceCodeLink;
	}

	public void setSourceCodeLink(String sourceCodeLink) {
		this.sourceCodeLink = sourceCodeLink;
	}

	@Column(name = "source_code_size", length = 20)
	public String getSourceCodeSize() {
		return this.sourceCodeSize;
	}

	public void setSourceCodeSize(String sourceCodeSize) {
		this.sourceCodeSize = sourceCodeSize;
	}

	@Column(name = "total_download")
	public Integer getTotalDownload() {
		return this.totalDownload;
	}

	public void setTotalDownload(Integer totalDownload) {
		this.totalDownload = totalDownload;
	}

}
