package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JavaQuiz generated by hbm2java
 */
@Entity
@Table(name = "java_quiz", catalog = "aminfo")
public class JavaQuiz implements java.io.Serializable {

	private Integer id;
	private Integer questionCount;
	private String dificultyLevel;
	private Date createDate;
	private String name;
	private String status;
	private Integer timeMinuties;

	public JavaQuiz() {
	}

	public JavaQuiz(Date createDate) {
		this.createDate = createDate;
	}

	public JavaQuiz(Integer questionCount, String dificultyLevel, Date createDate, String name, String status,
			Integer timeMinuties) {
		this.questionCount = questionCount;
		this.dificultyLevel = dificultyLevel;
		this.createDate = createDate;
		this.name = name;
		this.status = status;
		this.timeMinuties = timeMinuties;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "question_count")
	public Integer getQuestionCount() {
		return this.questionCount;
	}

	public void setQuestionCount(Integer questionCount) {
		this.questionCount = questionCount;
	}

	@Column(name = "dificulty_level", length = 20)
	public String getDificultyLevel() {
		return this.dificultyLevel;
	}

	public void setDificultyLevel(String dificultyLevel) {
		this.dificultyLevel = dificultyLevel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "time_minuties")
	public Integer getTimeMinuties() {
		return this.timeMinuties;
	}

	public void setTimeMinuties(Integer timeMinuties) {
		this.timeMinuties = timeMinuties;
	}

}
