package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JavaPost generated by hbm2java
 */
@Entity
@Table(name = "java_post", catalog = "aminfo")
public class JavaPost implements java.io.Serializable {

	private Integer id;
	private Metadata metadata;
	private String title;
	private String shortDesc;
	private String description;
	private String tags;
	private String attachment;
	private String attachmentType;
	private String postedBy;
	private Integer posterId;
	private Date datetime;
	private Integer status;
	private Integer totalView;
	private Integer childPost;

	public JavaPost() {
	}

	public JavaPost(Date datetime) {
		this.datetime = datetime;
	}

	public JavaPost(Metadata metadata, String title, String shortDesc, String description, String tags,
			String attachment, String attachmentType, String postedBy, Integer posterId, Date datetime, Integer status,
			Integer totalView, Integer childPost) {
		this.metadata = metadata;
		this.title = title;
		this.shortDesc = shortDesc;
		this.description = description;
		this.tags = tags;
		this.attachment = attachment;
		this.attachmentType = attachmentType;
		this.postedBy = postedBy;
		this.posterId = posterId;
		this.datetime = datetime;
		this.status = status;
		this.totalView = totalView;
		this.childPost = childPost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "metatag")
	public Metadata getMetadata() {
		return this.metadata;
	}

	public void setMetadata(Metadata metadata) {
		this.metadata = metadata;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "short_desc", length = 2000)
	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "tags", length = 200)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Column(name = "attachment", length = 200)
	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	@Column(name = "attachment_type", length = 100)
	public String getAttachmentType() {
		return this.attachmentType;
	}

	public void setAttachmentType(String attachmentType) {
		this.attachmentType = attachmentType;
	}

	@Column(name = "posted_by", length = 50)
	public String getPostedBy() {
		return this.postedBy;
	}

	public void setPostedBy(String postedBy) {
		this.postedBy = postedBy;
	}

	@Column(name = "poster_id")
	public Integer getPosterId() {
		return this.posterId;
	}

	public void setPosterId(Integer posterId) {
		this.posterId = posterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", nullable = false, length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "total_view")
	public Integer getTotalView() {
		return this.totalView;
	}

	public void setTotalView(Integer totalView) {
		this.totalView = totalView;
	}

	@Column(name = "child_post")
	public Integer getChildPost() {
		return this.childPost;
	}

	public void setChildPost(Integer childPost) {
		this.childPost = childPost;
	}

}
