package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Metadata generated by hbm2java
 */
@Entity
@Table(name = "metadata", catalog = "aminfo")
public class Metadata implements java.io.Serializable {

	private Integer id;
	private String title;
	private String link;
	private String description;
	private String image;
	private Date datetime;
	private Integer status;
	private String keywords;
	private Set javaPosts = new HashSet(0);
	private Set users = new HashSet(0);

	public Metadata() {
	}

	public Metadata(Date datetime) {
		this.datetime = datetime;
	}

	public Metadata(String title, String link, String description, String image, Date datetime, Integer status,
			String keywords, Set javaPosts, Set users) {
		this.title = title;
		this.link = link;
		this.description = description;
		this.image = image;
		this.datetime = datetime;
		this.status = status;
		this.keywords = keywords;
		this.javaPosts = javaPosts;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "link", length = 500)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", nullable = false, length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "keywords", length = 500)
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metadata")
	public Set getJavaPosts() {
		return this.javaPosts;
	}

	public void setJavaPosts(Set javaPosts) {
		this.javaPosts = javaPosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metadata")
	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
