package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuizQuestion generated by hbm2java
 */
@Entity
@Table(name = "quiz_question", catalog = "aminfo")
public class QuizQuestion implements java.io.Serializable {

	private Integer id;
	private String question;
	private String optionOne;
	private String optionTwo;
	private String optionThree;
	private String optionFour;
	private Integer status;
	private Date dateTime;
	private Integer quizId;
	private Integer answer;

	public QuizQuestion() {
	}

	public QuizQuestion(Date dateTime) {
		this.dateTime = dateTime;
	}

	public QuizQuestion(String question, String optionOne, String optionTwo, String optionThree, String optionFour,
			Integer status, Date dateTime, Integer quizId, Integer answer) {
		this.question = question;
		this.optionOne = optionOne;
		this.optionTwo = optionTwo;
		this.optionThree = optionThree;
		this.optionFour = optionFour;
		this.status = status;
		this.dateTime = dateTime;
		this.quizId = quizId;
		this.answer = answer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "question", length = 5000)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "option_one", length = 150)
	public String getOptionOne() {
		return this.optionOne;
	}

	public void setOptionOne(String optionOne) {
		this.optionOne = optionOne;
	}

	@Column(name = "option_two", length = 150)
	public String getOptionTwo() {
		return this.optionTwo;
	}

	public void setOptionTwo(String optionTwo) {
		this.optionTwo = optionTwo;
	}

	@Column(name = "option_three", length = 150)
	public String getOptionThree() {
		return this.optionThree;
	}

	public void setOptionThree(String optionThree) {
		this.optionThree = optionThree;
	}

	@Column(name = "option_four", length = 150)
	public String getOptionFour() {
		return this.optionFour;
	}

	public void setOptionFour(String optionFour) {
		this.optionFour = optionFour;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", nullable = false, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "quiz_id")
	public Integer getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Integer quizId) {
		this.quizId = quizId;
	}

	@Column(name = "answer")
	public Integer getAnswer() {
		return this.answer;
	}

	public void setAnswer(Integer answer) {
		this.answer = answer;
	}

}
