package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TagsRelation generated by hbm2java
 */
@Entity
@Table(name = "tags_relation", catalog = "aminfo")
public class TagsRelation implements java.io.Serializable {

	private Integer id;
	private String tag;
	private String nextTo;
	private Integer noOfUse;
	private Integer priority;

	public TagsRelation() {
	}

	public TagsRelation(String tag, String nextTo, Integer noOfUse, Integer priority) {
		this.tag = tag;
		this.nextTo = nextTo;
		this.noOfUse = noOfUse;
		this.priority = priority;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tag", length = 100)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "next_to", length = 100)
	public String getNextTo() {
		return this.nextTo;
	}

	public void setNextTo(String nextTo) {
		this.nextTo = nextTo;
	}

	@Column(name = "no_of_use")
	public Integer getNoOfUse() {
		return this.noOfUse;
	}

	public void setNoOfUse(Integer noOfUse) {
		this.noOfUse = noOfUse;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

}
