package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "aminfo")
public class Tags implements java.io.Serializable {

	private Integer id;
	private String tag;
	private Integer noOfUse;
	private Integer status;

	public Tags() {
	}

	public Tags(String tag, Integer noOfUse, Integer status) {
		this.tag = tag;
		this.noOfUse = noOfUse;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tag", length = 200)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "no_of_use")
	public Integer getNoOfUse() {
		return this.noOfUse;
	}

	public void setNoOfUse(Integer noOfUse) {
		this.noOfUse = noOfUse;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
