package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserClick generated by hbm2java
 */
@Entity
@Table(name = "user_click", catalog = "aminfo")
public class UserClick implements java.io.Serializable {

	private Integer id;
	private String deviceUuid;
	private String pageInfo;
	private String pageTitle;
	private Date datetime;
	private String location;
	private String ipAddress;

	public UserClick() {
	}

	public UserClick(Date datetime) {
		this.datetime = datetime;
	}

	public UserClick(String deviceUuid, String pageInfo, String pageTitle, Date datetime, String location,
			String ipAddress) {
		this.deviceUuid = deviceUuid;
		this.pageInfo = pageInfo;
		this.pageTitle = pageTitle;
		this.datetime = datetime;
		this.location = location;
		this.ipAddress = ipAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "device_uuid", length = 20)
	public String getDeviceUuid() {
		return this.deviceUuid;
	}

	public void setDeviceUuid(String deviceUuid) {
		this.deviceUuid = deviceUuid;
	}

	@Column(name = "page_info", length = 2000)
	public String getPageInfo() {
		return this.pageInfo;
	}

	public void setPageInfo(String pageInfo) {
		this.pageInfo = pageInfo;
	}

	@Column(name = "page_title", length = 200)
	public String getPageTitle() {
		return this.pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		this.pageTitle = pageTitle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", nullable = false, length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "location", length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "ip_address", length = 20)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
