package org.project.spring.model;
// Generated Dec 20, 2017 12:45:06 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserQuizDashboard generated by hbm2java
 */
@Entity
@Table(name = "user_quiz_dashboard", catalog = "aminfo")
public class UserQuizDashboard implements java.io.Serializable {

	private Integer id;
	private String deviceUuid;
	private Integer userId;
	private Integer quizId;
	private String quizName;
	private Integer score;

	public UserQuizDashboard() {
	}

	public UserQuizDashboard(String deviceUuid, Integer userId, Integer quizId, String quizName, Integer score) {
		this.deviceUuid = deviceUuid;
		this.userId = userId;
		this.quizId = quizId;
		this.quizName = quizName;
		this.score = score;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "device_uuid", length = 20)
	public String getDeviceUuid() {
		return this.deviceUuid;
	}

	public void setDeviceUuid(String deviceUuid) {
		this.deviceUuid = deviceUuid;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "quiz_id")
	public Integer getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Integer quizId) {
		this.quizId = quizId;
	}

	@Column(name = "quiz_name", length = 20)
	public String getQuizName() {
		return this.quizName;
	}

	public void setQuizName(String quizName) {
		this.quizName = quizName;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

}
